# Generated by Django 2.2.3 on 2019-07-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_auto_20190709_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objcets',
            name='object_createtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
