# Generated by Django 2.2.3 on 2019-07-18 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190711_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='assert_info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='testcase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.Testcases'),
        ),
    ]
