# Generated by Django 2.2.3 on 2019-07-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0003_testcases_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_url', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=1)),
                ('method', models.CharField(max_length=20)),
                ('agreement', models.CharField(max_length=20)),
                ('describe', models.TextField(max_length=1000)),
                ('parameter', models.CharField(max_length=2048)),
                ('testcase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.Testcases')),
            ],
            options={
                'db_table': 'api',
            },
        ),
    ]
