# Generated by Django 2.2.3 on 2019-07-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190718_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='re_func',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='testcase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.Testcases'),
        ),
    ]
