# Generated by Django 2.2.3 on 2019-07-10 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_auto_20190709_1558'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='object_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='object.Objcets'),
        ),
    ]
