# Generated by Django 2.2.3 on 2019-08-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='times',
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
