# Generated by Django 2.2.3 on 2019-07-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='objcets',
            table='objects',
        ),
    ]
