# Generated by Django 2.2.3 on 2019-07-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_products_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='testcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=300)),
                ('creat_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
            ],
            options={
                'db_table': 'testcases',
            },
        ),
    ]
